# @package _global_
defaults:
  - default

# Override for profiling runs
max_epochs: 3
batch_size: 256
num_workers: 2

# Disable some features for cleaner profiling
model:
  visualize_mar: false
  mar_viz_epochs: 99  # Effectively disable during short profiling runs

# Lightning Trainer settings for profiling
trainer:
  accelerator: auto
  devices: 
    - ${device_id}
  max_epochs: ${training.max_epochs}
  precision: 16-mixed
  enable_progress_bar: false  # Cleaner profiling output 